### ISSUE TITLE
Uvozila a samo poslabša

### ISSUE THREAD

**Issue by spelapovrzenic** [spelapovrzenic/APPR-2014-15#11]
Uvozila sem konfiguracijo za pisave, vendar sedaj ko vse poženem, ko odprem poročilo, so povsod na mojih grafih čudni  znakci, sploh ne čke, tako da me zanima če sem naredila kaj narobe.
Namestite paket extrafont.
    Uvozite paket extrafont z library(extrafont).
    Izvedite ukaz font_import().
    Izvedite ukaz loadfonts().
vse te ukaze sem naredila, nato še enkrat pognala projekt.r, nato pa odprla poročilo in se je vse samo poslabšalo. Ali moram mogoče še kaj dodatno prav v poročilo.tex napisati?
Hvala za odgovor in lep pozdrav

**Comment by jaanos** [comment]
Nisem uspel pri sebi ponoviti tega, tako da ne vem točno, kaj bi bilo krivo za to. Lahko pa poskusiš nadomestiti ukaze `pdf` s `cairo_pdf`. Ta deluje podobno, le parametra `paper` ne pozna, tako da je potrebno višino in širino papirja v inčih podati ročno. Poleg tega je potrebno nastaviti še parameter `onefile = TRUE`, če želiš izpisovati več grafov v eno datoteko. V `grafi.r` lahko torej poskusiš tako:
```R
cairo_pdf("slike/grafi.pdf", width = 8.27, height = 11.69,
          family = "Arial", onefile = TRUE)
```
V `projekt.r` uvozi še program `fontconfig.r` (lahko takoj za `clearpdf.r`), da se bo uvozil paket `extrafont`. Nastavitev pisave s `pdf.options` sicer ne vpliva na ukaz `cairo_pdf`, ki mu je treba pisavo vsakič podati sproti.

**Comment by spelapovrzenic** [comment]
Aha super hvala, sem naredila tako, in sedaj vse deluje kot mora :)
